version: "3.9"
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db2
    volumes:
      - mongo-data:/data/db

  # node-mongo-api:
  #   stdin_open: true
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: node-mongo-api
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - ./:/usr/app 
  #     - /usr/app/node_modules
  #   ports:
  #     - "8000:8000"
  #   restart: always

volumes:
  mongo-data:
    driver: local
