version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5556:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  # prisma-postgres-api:
  #   stdin_open: true
  #   build:
  #     context: .
  #     args:
  #       COMMAND: ${COMMAND} 
  #     dockerfile: Dockerfile
  #   container_name: prisma-postgres-api
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./:/usr/app 
  #     - /usr/app/node_modules
  #   ports:
  #     - "8000:8000"
  #   restart: always

volumes:
  postgres-data:
  pgadmin-data:
